### ISSUE TITLE
Home Page Epic

### ISSUE THREAD

**Issue by Medic1111** [chingu-voyages/v40-bears-team-29#16]
To accomplish Home Page User stories:

- [x] As a logged user I want to access home so I can read the post
- [x] When I access the home page I can see a nav bar with links to the main posts with lead me to the Root, Login and Register which lead me to Auth
- [x] When I access the root and Im logged in, I can see my post and click edit, which leads me to Edit form
- [x] When I access the root and Im logged in, and I see one of my posts I can trigger a delete from there
- [x] When I go to the root page I want to access the create post button
- [x] When I click on the create new post I want to access the post creation form
- [x] When Im Logged in I want to see a nav bar with links to: post, logout, profile, account, new posts
- [x] When I am in the main page I want to sort posts by rank
- [x] When I go to a page that have posts and Im logged in I can Up vote a post
- [x] When I got to a page that has my post and Im logged in, I can remove my post
