### ISSUE TITLE
Navigation Epic

### ISSUE THREAD

**Issue by Medic1111** [chingu-voyages/v40-bears-team-29#17]
To accomplish this Epic we must satisfy:

- [x] When I click on a username or avatar and I am NOT logged in i am redirected to the Auth page
- [x] When I click on a username or avatar and I a  logged in i am redirected to the user page
- [x] When I click on a post I am redirected to the details-post page
- [x] If I go to the Auth page I am prompted to enter Username and password
- [x] When I add an URL related to auth in my browser Im taken to the login page
- [x] When I add an URL related to the post, I get the details page of that post
- [x] When I add a user profile URL and I am logged in I want to see the user's profile
- [x] When I add a user profile URL and I am NOT logged I am redirected to the Auth
- [x] When I add a user profile URL and I am logged in I want to see the user's post history
- [x] When I add a user profile URL and I am logged in I want to see the user's profile
