### ISSUE TITLE
manage sessions (login signup)

### ISSUE THREAD

**Issue by Medic1111** [chingu-voyages/v40-bears-team-29#18]
To accomplish this epic we must satisfy

- [x] As Not Logged user I want to register so I can post in the application
- [x] As Not Logged registered user I want to login to the application so I can use the features
- [x] As a logged user I want to update my account details such as Username, Password, Bio
- [x] As a logged user I want to Logout so I can access the App as a guest
