### ISSUE TITLE
Crud Epic

### ISSUE THREAD

**Issue by Medic1111** [chingu-voyages/v40-bears-team-29#19]
To accomplish this epic we must satisfy:

- [x] As a logged user I want to create Posts so I can share my travel experiences
- [x] When I go to my user profile and I am logged in I want to access the Edit page for each post to Update information
- [x] When I go to my profile page and I am logged in I want to have access to the delete button on each post
- [x] When I access the root and I am logged in, If I see one of my posts I can trigger a deletion from there
- [x] When I access the root and I am logged in, If I see one of my posts I can trigger an Edit from there
- [x] When I click on the create post button I want to access the create post form
